name: "Lint and Build"
on:
  - push
  #- pull_request
  #- workflow_dispatch
jobs:
  lint-scripts:
    #runs-on: koalaman/shellcheck-alpine
    # see https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: .github/scripts/

  build:
    needs: lint-scripts
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: ./github/scripts/buid-image.sh
        shell: bash

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2
      #- name: Build Dockerfile
      #  uses: docker/build-push-action@v4
      #  with:
      #    push: false
      #    outputs: type=docker,dest=/tmp/gcloud-kubectl-helm.tar
      #    #tags: "kiwigrid/gcloud-kubectl-helm:testing"
      #    tags: "giddel/gcloud-kubectl-helm:testing"
      #- name: Upload artifacts
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: images
      #    path: /tmp/*.tar
