name: "Lint and Build"
on:
  - push
  #- pull_request
  #- workflow_dispatch
jobs:
  lint-scripts:
    runs-on: koalaman/shellcheck-alpine
  steps:
    steps:
      - checkout
      - run:
          name: lint-scripts
          command: .github/lint-scripts.sh
  build:
    needs: lint-scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Dockerfile
        uses: docker/build-push-action@v4
        with:
          push: false
          outputs: type=docker,dest=/tmp/gcloud-kubectl-helm.tar
          #tags: "kiwigrid/gcloud-kubectl-helm:testing"
          tags: "giddel/gcloud-kubectl-helm:testing"
      #- name: Upload artifacts
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: images
      #    path: /tmp/*.tar
